# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.6

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    # From https://www.augustguang.com/travis-ci-for-python-and-r/
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh > /dev/null
    - bash miniconda.sh -b -p $HOME/miniconda > /dev/null
    - export PATH="$HOME/miniconda/bin:$PATH" > /dev/null
    - hash -r > /dev/null
    - conda config --set always_yes yes --set changeps1 no > /dev/null
    - conda update -q conda > /dev/null
    - conda info -a > /dev/null
    - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION > /dev/null
    - source activate test-env > /dev/null

    - pip install coverage > /dev/null
    - pip install coveralls > /dev/null
    - pip install flake8 > /dev/null
    - conda install -c conda-forge r r-base r-lmertest r-lsmeans rpy2
    - pip install -r requirements.txt


# a list of commands to run before the main script
before_script:
    - "flake8 pisa_analysis_tool"

# the actual commands to run
script:
    - coverage run -m unittest pisa_analysis_tool/tests/test_*.py

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
